version: '3'

services:

  app:
    container_name: app
    restart: always
    build: ./app
    ports:
      - 8000:8000
    networks:
      - custom_network
    command: gunicorn -w 1 -b :8000 app:app

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./infra-nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/pages/:/etc/nginx/pages/
      - .letsencrypt.sh:/etc/cron.monthly/letsencrypt.sh
    depends_on:
      - app
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge

