services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - cryptochecker
      - nginx-bot_reverse_proxy
    env_file:
      - .env
    volumes:
      - ./project:/home/project
    command: gunicorn -w 1 --preload -b :5001 app:app
    restart: on-failure
  redis:
    image: redis:latest
    networks:
      - cryptochecker
  worker:
    build: .
    image: app:latest
    command: celery -A project.app.celery worker -l info -Q default
    env_file:
      - .env
    volumes:
      - ./project:/home/project
    links:
      - redis
    depends_on:
      - redis
    networks:
      - cryptochecker
    restart: on-failure
  beat:
    build: .
    image: app:latest
    entrypoint: celery -A project.app.celery beat -l info
    env_file:
      - .env
    volumes:
      - ./project:/home/project
    networks:
      - cryptochecker
    restart: on-failure

networks:
  cryptochecker:
  nginx-bot_reverse_proxy:
    external: true
