"""initial schema (tables)

Revision ID: 20260429024004
Revises: 20260429000001
Create Date: 2026-04-29 02:40:04.492873
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '20260429024004'
down_revision = '20260429000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('open_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume_base', sa.Float(), nullable=True),
    sa.Column('volume_quote', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('open_time_utc', 'id'),
    sa.UniqueConstraint('source', 'base_asset', 'quote_asset', 'timeframe', 'open_time_utc', name='uq_candles_identity')
    )
    op.create_index('ix_candles_market_tf_time', 'candles', ['base_asset', 'quote_asset', 'timeframe', 'open_time_utc'], unique=False)
    op.create_index('ix_candles_source_tf_time', 'candles', ['source', 'timeframe', 'open_time_utc'], unique=False)
    op.create_table('catalog_coins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coingecko_id', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('market_cap_rank', sa.Integer(), nullable=True),
    sa.Column('is_stablecoin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coingecko_id', name='uq_catalog_coingecko_id')
    )
    op.create_index('ix_catalog_rank', 'catalog_coins', ['market_cap_rank'], unique=False)
    op.create_index('ix_catalog_symbol', 'catalog_coins', ['symbol'], unique=False)
    op.create_table('indicator_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('asof_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'base_asset', 'quote_asset', 'timeframe', 'asof_time_utc', name='uq_indicator_snapshot_identity')
    )
    op.create_index('ix_indicator_snapshots_market_tf_time', 'indicator_snapshots', ['base_asset', 'quote_asset', 'timeframe', 'asof_time_utc'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('entry_time_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_time_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('hold_candles', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_trades_market_open', 'paper_trades', ['base_asset', 'quote_asset', 'timeframe', 'exit_time_utc'], unique=False)
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('volatility_threshold', sa.Float(), nullable=False),
    sa.Column('app_mode', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_tracked_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('base_asset', sa.String(length=16), nullable=False),
    sa.Column('quote_asset', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['telegram_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'base_asset', 'quote_asset', name='uq_user_tracked_asset')
    )
    op.create_index('ix_user_tracked_assets_user', 'user_tracked_assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tracked_assets_user', table_name='user_tracked_assets')
    op.drop_table('user_tracked_assets')
    op.drop_table('user_settings')
    op.drop_table('telegram_users')
    op.drop_index('ix_paper_trades_market_open', table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index('ix_indicator_snapshots_market_tf_time', table_name='indicator_snapshots')
    op.drop_table('indicator_snapshots')
    op.drop_index('ix_catalog_symbol', table_name='catalog_coins')
    op.drop_index('ix_catalog_rank', table_name='catalog_coins')
    op.drop_table('catalog_coins')
    op.drop_index('ix_candles_source_tf_time', table_name='candles')
    op.drop_index('ix_candles_market_tf_time', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
