name: Master - Testing

on:
  push:
    branches:
      - 'feature/add-python-telegram-bot'

jobs:

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [ docker ]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
